config/routes.rb
Rails.application.routes.draw do
  root "public_recipes#index"
  devise_for :users
  resources :users 
  resources :foods
  resources :shopping_lists
  resources :recipes do
    resources :recipe_foods
  end

  resources :public_recipes
  
  
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "articles#index"
end

app/models/ability.rb
class Ability
  include CanCan::Ability

  def initialize(user)
    user ||= User.new
    can :read, Recipe

    return unless user.present?

    can :read, :all
    can :manage, Food, user: user
    can :manage, RecipeFood, user: user
    can :manage, Recipe, user:
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/food.rb
class Food < ApplicationRecord
  belongs_to :user
  has_many :recipe_foods, foreign_key: 'food_id', dependent: :destroy

  def count
    user.foods.length
    food.save
  end
end

app/models/recipe.rb
class Recipe < ApplicationRecord
  belongs_to :user
  has_many :recipe_foods, foreign_key: 'recipe_id', dependent: :destroy
end

app/models/recipe_food.rb
class RecipeFood < ApplicationRecord
  belongs_to :recipe
  belongs_to :food

  validates :quantity, presence: true
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_many :foods, foreign_key: 'user_id', dependent: :destroy
  has_many :recipes, foreign_key: 'user_id', dependent: :destroy

  validates :name, presence: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :configure_permitted_parameters, if: :devise_controller?

  private

  def configure_permitted_parameters
    default_parameters = %i[name]
    devise_parameter_sanitizer.permit(:sign_up, keys: default_parameters)
    devise_parameter_sanitizer.permit(:sign_in, keys: default_parameters)
  end
end

app/controllers/foods_controller.rb
class FoodsController < ApplicationController
  # before_action :set_food, only: %i[show edit update destroy]
  before_action :authenticate_user!

  # GET /foods or /foods.json
  def index
    @foods = Food.all
  end

  # GET /foods/1 or /foods/1.json
  def show; end

  # GET /foods/new
  def new
    @food = Food.new
    respond_to do |format|
      format.html { render :new, locals: { post: @food } }
    end
  end

  # POST /foods or /foods.json
  def create
    @food = Food.new(food_params)
    @food.user = current_user
    respond_to do |format|
      if @food.save
        format.html { redirect_to foods_path(current_user), notice: 'Food was successfully created.' }
        format.json { render :show, status: :created, location: @food }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @food.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /foods/1 or /foods/1.json

  # DELETE /foods/1 or /foods/1.json
  def destroy
    @user = current_user
    @food = Food.find(params[:id])
    @food.destroy

    respond_to do |format|
      format.html { redirect_to foods_url(@user.id), notice: 'Food was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private

  # Use callbacks to share common setup or constraints between actions.

  # Only allow a list of trusted parameters through.
  def food_params
    params.require(:food).permit(:name, :measurement_unit, :price, :quantity)
  end
end

app/controllers/public_recipes_controller.rb
class PublicRecipesController < ApplicationController
  #  before_action :authenticate_user!
  # GET /recipes or /recipes.json
  def index
    @public_recipes = Recipe.all.where(public: true).order(created_at: :desc)
  end
end

app/controllers/recipe_foods_controller.rb
class RecipeFoodsController < ApplicationController
  before_action :authenticate_user!

  def new
    @recipe_food = RecipeFood.new
    @foods = Food.where(user: current_user)
    @food = Food.find_by(id: @recipe_food.food_id)
  end

  def create
    @recipe = Recipe.find(params[:recipe_id])
    @recipe_foods = RecipeFood.new(recipe_food_params)
    @recipe_foods.recipe = @recipe
    respond_to do |format|
      if @recipe_foods.save
        format.html do
          redirect_to recipe_url(@recipe), notice: 'Recipe food was successfully created.'
        end
        format.json { render :show, status: :created, location: @recipe_food }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @recipe_food.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /recipe_foods/1 or /recipe_foods/1.json
  def destroy
    @recipe_food = RecipeFood.find(params[:id])
    @recipe = Recipe.find_by(id: params[:recipe_id])
    @recipe_food.destroy

    respond_to do |format|
      format.html do
        redirect_to recipe_url(current_user, @recipe), notice: 'Recipe food was successfully destroyed.'
      end
      format.json { head :no_content }
    end
  end

  private

  # Only allow a list of trusted parameters through.
  def recipe_food_params
    params.require(:recipe_food).permit(:food_id, :quantity)
  end
end

app/controllers/recipes_controller.rb
class RecipesController < ApplicationController
  before_action :authenticate_user!

  def index
    @recipes = Recipe.all
  end

  def show
    @recipe = Recipe.find(params[:id])
    @recipe_foods = RecipeFood.includes([:food]).where(recipe_id: params[:id])
  end

  def new
    recipe = Recipe.new
    respond_to do |format|
      format.html { render :new, locals: { recipe: } }
    end
  end

  def create
    @recipe = Recipe.new(recipe_params)
    @recipe.user = current_user
    respond_to do |format|
      if @recipe.save
        format.html { redirect_to recipes_path(current_user), notice: 'Recipe was successfully created.' }
        format.json { render :show, status: :created, location: @recipe }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @recipe.errors, status: :unprocessable_entity }
      end
    end
  end

  def destroy
    @recipe = Recipe.find(params[:id])
    @recipe.destroy

    respond_to do |format|
      format.html { redirect_to recipes_url, notice: 'Recipe was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private

  # Only allow a list of trusted parameters through.
  def recipe_params
    params.require(:recipe).permit(:name, :preperation_time, :cooking_time, :description, :public)
  end
end

app/controllers/shopping_lists_controller.rb
class ShoppingListsController < ApplicationController
  before_action :authenticate_user!

  def index
    @recipe_foods = RecipeFood
      .joins(:recipe)
      .group('food_id')
      .select('food_id, sum(quantity) as quantity')
      .where(recipes: { user: current_user })
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :set_user, only: %i[show edit update destroy]
  before_action :authenticate_user!

  # GET /users or /users.json
  def index
    @users = User.all
    @current_user = current_user
  end

  # GET /users/1 or /users/1.json
  def show; end

  # GET /users/new
  def new
    @user = User.new
  end

  # POST /users or /users.json
  def create
    @user = User.new(user_params)

    respond_to do |format|
      if @user.save
        format.html { redirect_to user_url(@user), notice: 'User was successfully created.' }
        format.json { render :show, status: :created, location: @user }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /users/1 or /users/1.json

  # DELETE /users/1 or /users/1.json
  def destroy
    @user.destroy

    respond_to do |format|
      format.html { redirect_to users_url, notice: 'User was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private

  # Use callbacks to share common setup or constraints between actions.
  def set_user
    @user = User.find(params[:id])
  end

  # Only allow a list of trusted parameters through.
  def user_params
    params.require(:user).permit(:name)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/foods_helper.rb
module FoodsHelper
end

app/helpers/recipe_foods_helper.rb
module RecipeFoodsHelper
end

app/helpers/recipes_helper.rb
module RecipesHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/foods/_food.html.erb
<tr>
  <td><%= food.name %></td>
  <td><%= food.measurement_unit %></td>
  <td><%= "$ #{food.price}" %></td>
  <td><%= " #{food.quantity} units" %></td>
  <td>
  <%= button_to "Destroy this food", food_url(id: food.id), method: :delete %>
  </td>
</tr>

app/views/foods/_form.html.erb
<div class="recipe_information">
  <p style="color: white"><%= notice %></p>
  <h1>New Food</h1>
</div>
<section class='sign_up_container'>
<%= form_with model: food, url: foods_path, method: :post, local: true, scope: :food do |form| %>
    <% if food.errors.any? %>
      <div style="color: white">
        <h2><%= pluralize(food.errors.count, "error") %> prohibited this food from being saved:</h2>
        <ul>
          <% food.errors.each do |error| %>
            <li><%= error.full_message %></li>
          <% end %>
        </ul>
      </div>
    <% end %>
    <section class='sign_up_form'>
      <div class="field">
        <%= form.label :food, style: "display: block" %>
        <%= form.text_field :name %>
      </div>
      <div class="field">
        <%= form.label :measurement_unit, style: "display: block" %>
        <%= form.text_field :measurement_unit %>
      </div>
      <div class="field">
        <%= form.label :price, style: "display: block" %>
        <%= form.number_field :price %>
      </div>
      <div class="field">
        <%= form.label :quantity, style: "display: block" %>
        <%= form.number_field :quantity %>
      </div>
      <div class="field">
        <%= form.submit "Add food", class: 'button sign_up' %>
      </div>
    </section>
  <% end %>
</section>

app/views/foods/edit.html.erb
<h1>Editing food</h1>

<%= render "form", food: @food %>

<br>

<div>
  <%= link_to "Show this food", @food %> |
  <%= link_to "Back to foods", foods_path %>
</div>

app/views/foods/index.html.erb
<div class="recipe_information">
  <p style="color: white"><%= notice %></p>
    <%= link_to "Add Food", new_food_path, class: 'create_button new_food' %>
  <h1>Foods</h1>
</div>

<div id="foods">
  <table class ="recipe_table">
    <tr>
    <th>Name</th>
    <th>Measurement Unit</th>
    <th>Price</th>
    <th>Quantity</th>
    <th>Action</th>
  </tr>
  <% @foods.includes([:user]).each do |food| %>
    <%if can? :manage, food %>
      <%= render food %>
    <% end %>
  <%end%>
  </table>
</div>

app/views/foods/new.html.erb
<%= render "form", food: @food %>

<br>

<div>
  <%= link_to "Back to foods", foods_path %>
</div>

app/views/foods/show.html.erb
<p style="color: green"><%= notice %></p>

<%= render 'foods/food' %>

<div>
  <%= link_to "Edit this food", edit_food_path(@food) %> |
  <%= link_to "Back to foods", foods_path %>

  <%= button_to "Destroy this food", @food, method: :delete %>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>RecipeApp</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
    <%# <%= favicon_link_tag asset_path('favicon_meal.jpg') %>
  </head>

  <body>
  <nav class= "navigation_bar">
    <ul class= "nav_links">
      <li><%= link_to "Home", public_recipes_path %></li>
      <li><%= link_to "Show Foods", foods_path %></li>
      <li><%= link_to "Show Recipes", recipes_path %></li>
      <li><%= link_to "Public Recipes", public_recipes_path %></li>
      <li><%= link_to "Generate shooping list", shopping_lists_path %></li>
    </ul>
    <% if user_signed_in? %>
    <div class= "log_out_container">
      <%= button_to "Log out", destroy_user_session_path,
       { method: :delete, data: { turbo: false}, class: 'create_button log_out'} %>
    </div>
    <% end %>
  </nav>
    <%= yield %>
  </body>
</html>

app/views/public_recipes/index.html.erb
<% if @public_recipes.empty? %>
  <div class='notifications'>
    <h4>No Recipes made Public</h4>
  </div>
  <% else %>
    <section class='recipe_container'>
      <h1>Public Recipes</h1>
    <% @public_recipes.includes([:user]).each do |recipe| %>
      <article id="recipes" class="recipe_card public_recipe">
        <div class="name_container public_recipe">
          <p>
            <h2><%= link_to recipe.name, recipe_url(recipe.id), { class: 'recipe_name'} %></h2>
          </p>
          <p><strong>By:</strong>
            <%= recipe.user.name %>
          </p>
        </div>
        <div class="description_container public_recipe">
          <p>
          Total food items: 123
          </p>
          <p>Total price: 321
          </p>
        </div>
      </article>
    <% end %>
  <% end %>
  </section>

app/views/recipe_foods/_form.html.erb
<section class='sign_up_container'>
  <%= form_with url: recipe_recipe_foods_path,
    method: :post, local: true, scope: :recipe_food do |form| %>
      <% if recipe_food.errors.any? %>
       <div style="color: white">
          <h2><%= pluralize(recipe_food.errors.count, "error") %> Please enter a correct value in the field:</h2>
            <ul>
            <% recipe_food.errors.each do |error| %>
              <li><%= error.full_message %></li>
            <% end %>
            </ul>
        </div>
      <% end %>

  <section class='sign_up_form'>

    <h1>New recipe food</h1>


      <div class="field">
        <%= form.label :food_id, style: "display: block" %>
        <%= form.select :food_id, current_user.foods.map { |food| ["#{food.name} (#{food.measurement_unit})", food.id ] }, {}%>
      </div>

      <div class="field">
        <%= form.label :quantity, style: "display: block" %>
        <%= form.number_field :quantity, min: 1, max: 20000 %>
        (1 to 20000)
    </div>
      <div>
        <%= form.submit "Add ingredient", class: 'button sign_up'%>
      </div>
    <% end %>
  </section>
</section>

app/views/recipe_foods/_recipe_food.html.erb
<div id="<%= dom_id recipe_food %>">
  <p>
    <strong>Recipe:</strong>
    <%= recipe_food.recipe_id %>
  </p>

  <p>
    <strong>Food:</strong>
    <%= recipe_food.food_id %>
  </p>

  <p>
    <strong>Quantity:</strong>
    <%= recipe_food.quantity %>
  </p>

</div>

app/views/recipe_foods/edit.html.erb
<h1>Editing recipe food</h1>

<%= render "form", recipe_food: @recipe_food %>

<br>

<div>
  <%= link_to "Show this recipe food", @recipe_food %> |
  <%= link_to "Back to recipe foods", recipe_foods_path %>
</div>

app/views/recipe_foods/index.html.erb
<p style="color: green"><%= notice %></p>

<h1>Recipe foods</h1>

<div id="recipe_foods">
  <% @recipe_foods.each do |recipe_food| %>
    <%= render recipe_food %>
    <p>
      <%= link_to "Show this recipe food", recipe_food %>
    </p>
  <% end %>
</div>

<%= link_to "New recipe food", new_recipe_food_path %>

app/views/recipe_foods/new.html.erb
<%= render "form", recipe_food: @recipe_food %>

<div>
  <%= link_to "Back to recipe foods", recipes_url %>
</div>

app/views/recipe_foods/show.html.erb
<p style="color: green"><%= notice %></p>

<%= render @recipe_food %>

<div>
  <%= link_to "Edit this recipe food", edit_recipe_food_path(@recipe_food) %> |
  <%= link_to "Back to recipe foods", recipe_foods_path %>

  <%= button_to "Destroy this recipe food", @recipe_food, method: :delete %>
</div>

app/views/recipes/_form.html.erb
<section class='sign_up_container'>

  <section class='sign_up_form'>
    <h2>New recipe</h2>

  <%= form_with model: recipe, url: recipes_path, method: :post, local: true, scope: :recipe do |form| %>

    <div class= "field">
      <%= form.label :name, style: "display: block" %>
      <%= form.text_field :name %>
    </div>

    <div class= "field">
      <%= form.label :preperation_time, style: "display: block" %>
      <%= form.number_field :preperation_time, min: 1, max: 540 %> 1 to 540 Minutes
    </div>

    <div class= "field">
      <%= form.label :cooking_time, style: "display: block" %>
      <%= form.number_field :cooking_time, min: 1, max: 540 %> 1 to 540 Minutes
    </div>

    <div class= "field">
      <%= form.label :description, style: "display: block" %>
      <%= form.text_area :description %>
    </div>

    <div class= "field">
      <%= form.label :public, style: "display: block" %>
      <%= form.check_box :public %>
    </div>

    <div>
      <%= form.submit "Create recipe", class: 'button sign_up'%>
    </div>
    <% end %>
  </section>
</section>

app/views/recipes/_recipe.html.erb
<div id="<%= dom_id recipe %>">

  <p>
    <strong>Name:</strong>
    <%= recipe.name %>
  </p>

  <p>
    <strong>Preperation time:</strong>
    <%= recipe.preperation_time %> minutes
  </p>

  <p>
    <strong>Cooking time:</strong>
    <%= recipe.cooking_time %> minutes
  </p>

  <p>
    <strong>Description:</strong>
    <%= recipe.description %>
  </p>

  <p>
    <strong>Public:</strong>
    <%= recipe.public %>
  </p>

</div>

app/views/recipes/edit.html.erb
<h1>Editing recipe</h1>

<%= render "form", recipe: @recipe %>

<br>

<div>
  <%= link_to "Show this recipe", @recipe %> |
  <%= link_to "Back to recipes", recipes_path %>
</div>

app/views/recipes/index.html.erb
<p style="color: green"><%= notice %></p>

<% if @recipes.empty? %>
  <div class='notifications'>
    <h4>This user hasn't create any recipes yet</h4>
    <%= link_to "New recipe", new_recipe_url, class: 'create_button new_recipe' %>
  </div>
  <% else %>
  <section class='recipe_container'>
  <h1>Recipes</h1>
  <%= link_to "New recipe", new_recipe_url, class: 'create_button new_recipe' %>
  <% @recipes.includes([:user]).each do |recipe| %>
  <article id="recipes" class="recipe_card">
    <div class="name_container">
        <%= link_to recipe.name, recipe_url(recipe.id), { class: 'recipe_name'} %>
        <% if can? :manage, recipe%>
          <%= button_to "REMOVE", recipe_url(recipe.id), method: :delete %>
        <% end %>
    </div>
    <div class="description_container">
      <p class="recipe_description"><%= recipe.description %></p>
    </div>
  </article>
    <% end %>
  <% end %>
</section>

app/views/recipes/new.html.erb
<%= render "form", recipe: @recipe %>

<br>

<div>
  <%= link_to "Back to recipes", recipes_url %>
</div>

app/views/recipes/show.html.erb
<div class="recipe_information">
  <p style="color: white"><%= notice %></p>
  <h1>Recipe <%=@recipe.name%></h1>
</div>
<section class= "recipe_detail">
  <div>
    <p>Cooking time: <%=@recipe.cooking_time%></p>
    <p>Preperation time: <%=@recipe.preperation_time%></p>
    <p>Steps go here... </p>
  </div>
  <div>
    <h3>Public</h3>
    <label class="switch">
      <input type="checkbox">
      <span class="slider round"></span>
    </label>
  </div>
</section>
<div class="shopping_button_container">
  <button>
    <%= link_to "Generate shooping list", shopping_lists_path %>
  </button>
  <button>
    <%= link_to "Add ingredients", new_recipe_recipe_food_url(@recipe) %>
  </button>
</div>
<div class="container_recipe_line">
	<hr class="recipe_line" />
</div>
  <table class ="recipe_table">
    <tr>
      <th>Food</th>
      <th>Quantity</th>
      <th>Value</th>
      <th>Actions</th>
    </tr>
  <% @recipe_foods.each do |elem| %>
    <tr>
      <td><%= elem.food[:name] %></td>
      <td><%= elem[:quantity] %></td>
      <td><%= "$ #{elem.food[:price] * elem[:quantity]}" %></td>
      <td>
      <% if can? :manage, @recipe %>
          <%= button_to "REMOVE", recipe_recipe_food_path( @recipe, elem), method: :delete %>
      <% end %>
      </td>
    </tr>
    <% end %>
  </table>
<div>
  <%= link_to "Back to recipes", recipes_url(@recipe.id) %>
</div>

app/views/shopping_lists/index.html.erb
<div class="recipe_information">
  <p style="color: white"><%= notice %></p>
  <h1>Shopping List</h1>
  <% sum_items = 0
  total_value = 0 %>
</div>
  <table class ="recipe_table">
    <tr>
      <th>Food</th>
      <th>Quantity</th>
      <th>Value</th>
    </tr>
    <% @recipe_foods.each do |recipe_food| %>
    <% if recipe_food.quantity > recipe_food.food.quantity %>
    <% aux = recipe_food.quantity - recipe_food.food.quantity %>
    <% sum_items += aux 
        total_value += aux * recipe_food.food.price %>
    <tr>
        <td><%= recipe_food.food.name %></td>
        <td><%= aux %> <%= recipe_food.food.measurement_unit %></td>
        <td><%= number_to_currency(recipe_food.food.price * aux, unit: '$', precision: 0) %></td>
    </tr>
    <% end %>
    <% end %>
  </table>
  <div class="missing_shopping_list">
    <p>Amount of food items to buy: <%= sum_items %></p>
    <p>Total value of food needed: $ <%= total_value %></p>
  </div>

app/views/users/_form.html.erb
<%= form_with(model: user) do |form| %>
  <% if user.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(user.errors.count, "error") %> prohibited this user from being saved:</h2>

      <ul>
        <% user.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div>
    <%= form.label :name, style: "display: block" %>
    <%= form.text_field :name %>
  </div>

  <div>
    <%= form.submit %>
  </div>
<% end %>

app/views/users/_user.html.erb
<div id="<%= dom_id user %>">
  <p>
    <strong>Name:</strong>
    <%= user.name %>
  </p>

</div>

app/views/users/edit.html.erb
<h1>Editing user</h1>

<%= render "form", user: @user %>

<br>

<div>
  <%= link_to "Show this user", @user %> |
  <%= link_to "Back to users", users_path %>
</div>

app/views/users/index.html.erb
<p style="color: green"><%= notice %></p>

<h1>Users</h1>

<div id="users">
  <% @users.each do |user| %>
    <%= render user %>
    <p>
      <%= link_to "Show this user", user %>
    </p>
  <% end %>
</div>

app/views/users/new.html.erb
<h1>New user</h1>

<%= render "form", user: @user %>

<br>

<div>
  <%= link_to "Back to users", users_path %>
</div>

app/views/users/show.html.erb
<p style="color: green"><%= notice %></p>

<%= render @user %>

<div>
  <%= link_to "Edit this user", edit_user_path(@user) %> |
  <%= link_to "Back to users", users_path %>

  <%= button_to "Destroy this user", @user, method: :delete %>
</div>